apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-nginx-deployment
  labels:
    env: cp-dev-server
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: cp-dev-server
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
